## 代码2-1

In [1]:
import numpy as np
arr1 = np.array([91, 88, 96, 79]) #创建一维数组
print('小李的考试成绩为：',arr1)

小李的考试成绩为： [91 88 96 79]


In [2]:
arr2 = np.array([[91, 88, 96, 79], [85, 98, 77,81]]) #创建二维数组
print('小李和小王的考试成绩为：\n',arr2)

小李和小王的考试成绩为：
 [[91 88 96 79]
 [85 98 77 81]]


## 代码2-2

In [3]:
import numpy as np
np.zeros((3, 4)) #创建元素值全是0 的数组

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
import numpy as np
np.zeros((3, 4)) #创建元素值全是0 的数组

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 代码2-3

In [5]:
import numpy as np
#查看数组的属性
arr2 = np.array([[91, 88, 96, 79], [85, 98, 77,81]])
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)

2
(2, 4)
8
int32
4


## 代码2-4

In [6]:
import numpy as np
#创建一个空数组
np.empty((5, 2))

array([[4.67296746e-307, 1.69121096e-306],
       [1.29061142e-306, 1.89146896e-307],
       [7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.29061142e-306],
       [9.79111946e-307, 1.02356521e-306]])

## 代码2-5

In [8]:
import numpy as np
#利用arange 函数创建数组
arr2 =np.arange(1, 20, 5)
arr3 = np.arange(0, 10)
arr4 = np.arange(10)
arr5 = np.arange(0, 1, 0.1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)

[ 1  6 11 16]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


## 代码2-6

In [9]:
import numpy as np
print(np.random.random(10)) #无约束条件下的随机数

[0.1022617  0.33955668 0.16937647 0.83156592 0.50454341 0.39108049
 0.33050987 0.26248508 0.11768226 0.79992113]


## 代码2-7

In [10]:
import numpy as np
print(np.random.rand(3,4)) #生成指定shape 的服从均匀分布的随机数

[[0.93068026 0.01908694 0.11533071 0.9271137 ]
 [0.99131384 0.52204423 0.73550957 0.30191627]
 [0.18750926 0.43731689 0.53804674 0.29394334]]


## 代码2-8

In [11]:
import numpy as np
print(np.random.randn(3,4)) #生成指定shape 的服从正态分布的随机数

[[ 0.12502254 -1.49628441 -0.11820044  0.18939086]
 [-1.32940069 -1.33298551  1.18490512  0.68274472]
 [-0.24871347  0.6886293  -0.19168229  0.86482268]]


## 代码2-9

In [13]:
import numpy as np
#生成随机数的种子
np.random.seed(0)
#随机生成包含5 个元素的浮点型数组
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [14]:
#生成随机数的种子
np.random.seed(0)
#随机生成包含5 个元素的浮点型数组
np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

# 代码2-10

In [ ]:
import numpy as np
#生成随机数的种子
np.random.seed(1)
#随机生成包含5 个元素的浮点型数组
np.random.rand(5)

In [15]:
#生成随机数的种子
np.random.seed(2)
#随机生成包含5 个元素的浮点型数组
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

## 代码2-11

In [16]:
import numpy as np
arr2 = np.array([[91, 88, 96, 79], [85, 98, 77,81]])
print(arr2.dtype)

int32


## 代码2-12

In [17]:
import numpy as np
arr3 = np.array([[91, 88, 96, 79], [85, 98, 77,81]],dtype='f')
print(arr3.dtype)

float32


## 代码2-13

In [18]:
import numpy as np
arr2 = np.array([[91, 88, 96, 79], [85, 98, 77,81]])
print(arr2.dtype)
#数据类型转换为float64
float_data = arr2.astype(np.float64)
print(float_data.dtype)

int32
float64


## 代码2-14

In [19]:
import numpy as np
score1=np.array([98,77,87,81])
print('4 位同学的语文考试成绩为：',score1)
score2=np.array([82,95,79,92])
print('4 位同学的数学考试成绩为：',score2)
print('4 位同学两门课考试成绩之和为：',score1+score2)

4 位同学的语文考试成绩为： [98 77 87 81]
4 位同学的数学考试成绩为： [82 95 79 92]
4 位同学两门课考试成绩之和为： [180 172 166 173]


## 代码2-15

In [2]:
import numpy as np
arr1=np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
arr1.shape

(4, 3)

In [4]:
arr2=np.array([1,2,3])
arr2.shape

(3,)

In [22]:
arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [23]:
arr3=np.array([[1],[2],[3],[4]])
arr3.shape

(4, 1)

In [24]:
arr1+arr3

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

## 代码2-16

In [25]:
import numpy as np
score= np.array([[91, 88, 96, 79], [85, 98, 77,81]])
rate=0.8
print(score*rate)

[[72.8 70.4 76.8 63.2]
 [68.  78.4 61.6 64.8]]


## 代码2-17

In [26]:
import numpy as np
arr1 = np.array([91.5, 88.4, 96.8, 79.2])
#计算各元素的平方根
print(np.sqrt(arr1))
#计算各元素的平方
print(np.square(arr1))
#计算各元素的绝对值
print(np.abs(arr1))
#计算小于或等于各元素的最大整数
print(np.floor(arr1))
#计算大于或等于各元素的最小整数
print(np.ceil(arr1))
#判断各元素的正负
print(np.sign(arr1))
#将各元素四舍五入
print(np.rint(arr1))

[9.56556323 9.40212742 9.8386991  8.89943818]
[8372.25 7814.56 9370.24 6272.64]
[91.5 88.4 96.8 79.2]
[91. 88. 96. 79.]
[92. 89. 97. 80.]
[1. 1. 1. 1.]
[92. 88. 97. 79.]


## 代码2-18

In [27]:
import numpy as np
score1=np.array([98,77,87,81])
print('4 位同学的语文考试成绩为：',score1)
score2=np.array([82,95,79,92])
print('4 位同学的数学考试成绩为：',score2)

4 位同学的语文考试成绩为： [98 77 87 81]
4 位同学的数学考试成绩为： [82 95 79 92]


In [28]:
#计算两个数组之和
print(np.add(score1,score2))
#计算两个数组之差
print(np.subtract(score1,score2))
#数组元素级最大值比较
print(np.maximum(score1,score2))
#数组元素级最小值比较
print(np.minimum(score1,score2))
#数组元素级的比较操作
print(np.greater(score1,score2))

[180 172 166 173]
[ 16 -18   8 -11]
[98 95 87 92]
[82 77 79 81]
[ True False  True False]


## 代码2-19

In [30]:
import numpy as np
a=np.arange(12)
print(a)
print(a.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 代码2-20

In [32]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]).ravel()
print(a)

[1 2 3 4 5 6 7 8 9]


In [34]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]).flatten()
print(a)

[1 2 3 4 5 6 7 8 9]


In [35]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]).flatten('F')
print(a)

[1 4 7 2 5 8 3 6 9]


## 代码2-21

In [37]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[ 2,4,6],[ 8,10,12],[14,16,18]])
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [38]:
print(np.hstack((a1,a2))) #横向组合
print(np.vstack((a1,a2))) #纵行组合

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [39]:
print(np.concatenate((a1,a2),axis=1)) #横向组合
print(np.concatenate((a1,a2),axis=0)) #纵行组合

[[ 1  2  3  2  4  6]
 [ 4  5  6  8 10 12]
 [ 7  8  9 14 16 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## 代码2-22

In [40]:
import numpy as np
score= np.array([[91, 88, 96, 79], [85, 98, 77,81]])
print(score)
#计算所有元素的和
print(score.sum())
#计算0 轴元素的和
print(score.sum(axis=0))
#计算1 轴元素的和
print(score.sum(axis=1))
#计算所有元素的平均值
print(score.mean())
#计算0 轴元素的平均值
print(score.mean(axis=0))
#计算1 轴元素的平均值
print(score.mean(axis=1))

[[91 88 96 79]
 [85 98 77 81]]
695
[176 186 173 160]
[354 341]
86.875
[88.  93.  86.5 80. ]
[88.5  85.25]


## 代码2-23

In [41]:
import numpy as np
score= np.array([[91, 88, 96, 79], [85, 98, 77,81]])
print(score)
#计算所有元素的最小值
print(score.min())
#计算0 轴元素的最小值
print(score.min(axis=0))
#计算1 轴元素的最小值
print(score.min(axis=1))
#计算所有元素的最大值
print(score.max())
#计算0 轴元素的最大值
print(score.max(axis=0))
#计算1 轴元素的最大值
print(score.max(axis=1))

[[91 88 96 79]
 [85 98 77 81]]
77
[85 88 77 79]
[79 77]
98
[91 98 96 81]
[96 98]


## 代码2-24

In [42]:
import numpy as np
score= np.array([[91, 88, 96, 79], [85, 98, 77,81]])
print(score)
#所有元素最小值的索引
print(score.argmin())
#0 轴元素最小值的索引
print(score.argmin(axis=0))
#1 轴元素最小值的索引
print(score.argmin(axis=1))
#所有元素最大值的索引
print(score.argmax())
#0 轴元素最大值的索引
print(score.argmax(axis=0))
#1 轴元素最大值的索引
print(score.argmax(axis=1))

[[91 88 96 79]
 [85 98 77 81]]
6
[1 0 1 0]
[3 2]
5
[0 1 0 1]
[2 1]


## 代码2-25

In [43]:
import numpy as np
score= np.array([[91, 88, 96, 79], [85, 98, 77,81]])
print(score)
#所有元素的累计和
print(score.cumsum())
#0 轴元素的累计和
print(score.cumsum(axis=0))
#1 轴元素的累计和
print(score.cumsum(axis=1))
#所有元素的累计积
print(score.cumprod())
#0 轴元素的累计积
print(score.cumprod(axis=0))
#1 轴元素的累计积
print(score.cumprod(axis=1))

[[91 88 96 79]
 [85 98 77 81]]
[ 91 179 275 354 439 537 614 695]
[[ 91  88  96  79]
 [176 186 173 160]]
[[ 91 179 275 354]
 [ 85 183 260 341]]
[         91        8008      768768    60732672   867309824  -902983168
  -810227200 -1203893760]
[[  91   88   96   79]
 [7735 8624 7392 6399]]
[[      91     8008   768768 60732672]
 [      85     8330   641410 51954210]]


## 代码2-26

In [44]:
import numpy as np
arr1 = np.array([91, 88, 96, 79])
arr1.sort()
print(arr1)
arr2 = np.array([[91, 88, 96, 79], [85, 98, 77,81]])
arr2.sort()
print(arr2)

[79 88 91 96]
[[79 88 91 96]
 [77 81 85 98]]


In [45]:
arr = np.array([[91, 88, 96, 79], [85, 98, 77,81]])
#沿着0 轴对元素排序
arr.sort(axis=0)
print(arr)

[[85 88 77 79]
 [91 98 96 81]]


## 代码2-27

In [46]:
import numpy as np
arr1 = np.array([8,4,5,2,9,6])
arr1.sort()
print(arr1)

[2 4 5 6 8 9]


In [47]:
arr2 = np.array([8,4,5,2,9,6])
print(arr2.argsort())
print(arr2)

[3 1 2 5 0 4]
[8 4 5 2 9 6]


## 代码2-28

In [49]:
import numpy as np
score1=np.array([[96,75,88],[78,92,99],[85,89,90]])
print('小李,小王、小赵的语数外成绩为：\n',score1)

小李,小王、小赵的语数外成绩为：
 [[96 75 88]
 [78 92 99]
 [85 89 90]]


In [50]:
print(score1.trace()) #使用trace()方法
print(np.trace(score1)) #使用trace()函数

278
278


## 代码2-29

In [51]:
import numpy as np
arr_x = np.array([[1, 2, 3], [4, 5, 6]])
arr_y = np.array([[1, 2], [3, 4], [5, 6]])
#使用dot()函数
print(np.dot(arr_x, arr_y))

[[22 28]
 [49 64]]


In [52]:
arr_x = np.array([[1, 2, 3], [4, 5, 6]])
arr_y = np.array([[1, 2], [3, 4], [5, 6]])
#使用dot()方法
print(arr_x.dot(arr_y))

[[22 28]
 [49 64]]
