## 代码3-1

In [1]:
import pandas as pd
s = pd.Series()
#创建一个空的Series
print(s)

Series([], dtype: float64)


C:\Users\hemen\AppData\Local\Temp/ipykernel_17132/2472686533.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


## 代码3-2

In [5]:
import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
#从ndarray 创建一个Series
print(s)

0    a
1    b
2    c
3    d
dtype: object


## 代码3-3

In [10]:
import pandas as pd
import numpy as np
data = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data)
#使用字典创建一个Series
print(s)

a    0.0
b    1.0
c    2.0
dtype: float64


## 代码3-4

In [11]:
import pandas as pd
import numpy as np
s = pd.Series(5, index=[0, 1, 2, 3])
#使用标量创建一个Series
print(s)

0    5
1    5
2    5
3    5
dtype: int64


## 代码3-5

In [5]:
import pandas as pd
data = {'水果':['苹果','梨','草莓'],
'数量':[3,2,5],
'价格':[10,9,8]}
df = pd.DataFrame(data)
#使用包含列表的字典创建DataFrame
print(df)

   水果  数量  价格
0  苹果   3  10
1   梨   2   9
2  草莓   5   8


## 代码3-6

In [6]:
import pandas as pd
data = {
'platform': ['qq', 'weixin', 'weibo', 'taobao'],
'year': [2000, 2010, 2005, 2004],
'percent': [0.71, 0.89, 0.63, 0.82]
}
columns = ['year', 'platform', 'percent']
df = pd.DataFrame(data, columns=columns)
#按照给定的列顺序进行排序生成DataFrame
print(df)

   year platform  percent
0  2000       qq     0.71
1  2010   weixin     0.89
2  2005    weibo     0.63
3  2004   taobao     0.82


## 代码3-7

In [7]:
import pandas as pd
data = {
'platform': ['qq', 'weixin', 'weibo', 'taobao'],
'year': [2000, 2010, 2005, 2004],
'percent': [0.71, 0.89, 0.63, 0.82]
}
columns = ['year', 'platform', 'percent', 'count']
index = ['a', 'b', 'c', 'd']
df = pd.DataFrame(data, columns=columns, index=index)
print(df)

   year platform  percent count
a  2000       qq     0.71   NaN
b  2010   weixin     0.89   NaN
c  2005    weibo     0.63   NaN
d  2004   taobao     0.82   NaN


In [8]:
print(df['year'])
#可以使用列名获取到DataFrame 中该列的所有数据，返回一个Series

a    2000
b    2010
c    2005
d    2004
Name: year, dtype: int64


In [9]:
print(df.platform)
#也可以直接使用列名访问该列的所有数据

a        qq
b    weixin
c     weibo
d    taobao
Name: platform, dtype: object


In [10]:
print(df.loc['a'])
#获取index 为‘a’的行

year        2000
platform      qq
percent     0.71
count        NaN
Name: a, dtype: object


## 代码3-8

In [11]:
import pandas as pd
data = {'数量':{'苹果':3,'梨':2,'草莓':5},
'价格':{'苹果':10,'梨':9,'草莓':8}}
df = pd.DataFrame(data)
print(df)

    数量  价格
苹果   3  10
梨    2   9
草莓   5   8


## 代码3-9

In [12]:
import pandas as pd
data = {'水果':pd.Series(['苹果','梨','草莓']),
'数量':pd.Series([3,2,5]),
'价格':pd.Series([10,9,8])}
df = pd.DataFrame(data)
print(df)

   水果  数量  价格
0  苹果   3  10
1   梨   2   9
2  草莓   5   8


## 代码3-10

In [13]:
import pandas as pd
stu_info = pd.read_csv('./1.csv')
stu_info

Chinese  Math  English
0       88  11.0       22
1       33   NaN       30
2       85  32.0       90

## 代码3-11

In [6]:
import pandas as pd
stu_info = pd.read_csv('./1.csv',header=1,names=['语文','数学','英语'])
stu_info

语文    数学  英语
0  33   NaN  30
1  85  32.0  90

## 代码3-12

In [7]:
import pandas as pd
test_dict = {'id':[1,2,3,4,5,6],
'name':['Alice','Bob','Cindy','Eric','Helen','Grace '],
'Math':[90,89,99,78,97,93],
'English':[89,94,80,94,94,90]}
test_dict_df = pd.DataFrame(test_dict)
test_dict_df

id    name  Math  English
0   1   Alice    90       89
1   2     Bob    89       94
2   3   Cindy    99       80
3   4    Eric    78       94
4   5   Helen    97       94
5   6  Grace     93       90

In [8]:
new_columns = [92,94,89,77,87,91]
test_dict_df.insert(2,'Pyhsics',new_columns,allow_duplicates=True)
test_dict_df

id    name  Pyhsics  Math  English
0   1   Alice       92    90       89
1   2     Bob       94    89       94
2   3   Cindy       89    99       80
3   4    Eric       77    78       94
4   5   Helen       87    97       94
5   6  Grace        91    93       90

## 代码3-13

In [21]:
new_line = [7,'Iric',99,90]
test_dict_df.loc[6]= new_line
test_dict_df

id    name  math  english
0   1   Alice    90       89
1   2     Bob    89       94
2   3   Cindy    99       80
3   4    Eric    78       94
4   5   Helen    97       94
5   6  Grace     93       90
6   7    Iric    99       90

## 代码3-14

In [24]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
df = DataFrame(np.random.rand(12).reshape((3,4)),index = ['one', 'two', 'three'],columns= list('abcd'))
print(df)
type(df['a'])
df[['a','c']] # dataframe

              a         b         c         d
one    0.780072  0.456341  0.967519  0.395407
two    0.726652  0.199011  0.116251  0.728268
three  0.117667  0.974530  0.732884  0.582799


a         c
one    0.780072  0.967519
two    0.726652  0.116251
three  0.117667  0.732884

## 代码3-15

In [25]:
df.loc['one'] # 单独的行，返回的也是一个Series 对象

a    0.780072
b    0.456341
c    0.967519
d    0.395407
Name: one, dtype: float64

In [26]:
df.iloc[0:2]

a         b         c         d
one  0.780072  0.456341  0.967519  0.395407
two  0.726652  0.199011  0.116251  0.728268

## 代码3-16

In [9]:
import numpy as np
from pandas import Series, DataFrame
df1 = DataFrame(np.random.rand(12).reshape((3,4)),index = [3,2,1],columns= list('abcd'))
df1

a         b         c         d
3  0.976090  0.318833  0.469992  0.233669
2  0.142350  0.068466  0.053382  0.220739
1  0.404972  0.056564  0.990590  0.278227

In [10]:
df1.loc[2:1]

a         b         c         d
2  0.142350  0.068466  0.053382  0.220739
1  0.404972  0.056564  0.990590  0.278227

In [11]:
df1.iloc[0:3]#使用位置标签来进行索引切片处理

a         b         c         d
3  0.976090  0.318833  0.469992  0.233669
2  0.142350  0.068466  0.053382  0.220739
1  0.404972  0.056564  0.990590  0.278227

## 代码3-17

In [17]:
import numpy as np
a = np.array([[2,4],[8,5]])
print ('我们的数组是：')
print (a)
print ('\n')
print ('调用sort()函数：')
print (np.sort(a))
print ('\n')
print ('按列排序：')
print (np.sort(a, axis = 0))
print ('\n')

我们的数组是：
[[2 4]
 [8 5]]


调用sort()函数：
[[2 4]
 [5 8]]


按列排序：
[[2 4]
 [8 5]]




In [15]:
a

array([[2, 4],
       [8, 5]])

## 代码3-18

In [33]:
import pandas as pd
import numpy as np
#按索引排序
unsorted_df = pd.DataFrame(np.random.randn(4, 2),index=[1, 0, 3, 2],
columns=['col2', 'col1'])
print(unsorted_df)
print("------排序后 默认行 标签排序\n", unsorted_df.sort_index(ascending=False))
print("------排序后 默认列 排序\n", unsorted_df.sort_index(axis=1))

       col2      col1
1 -0.689926  0.483234
0  1.755189  1.314058
3  0.059299  1.300689
2 -0.833906 -0.422337
------排序后 默认行 标签排序
        col2      col1
3  0.059299  1.300689
2 -0.833906 -0.422337
1 -0.689926  0.483234
0  1.755189  1.314058
------排序后 默认列 排序
        col1      col2
1  0.483234 -0.689926
0  1.314058  1.755189
3  1.300689  0.059299
2 -0.422337 -0.833906


In [35]:
#按数值排序
d = {'Name': pd.Series(['Tom', 'James', 'Ricky', 'Vin', 'Steve',
'Minsu', 'Jack']), 'Age': pd.Series([25, 26, 25, 23, 30, 29, 23]),
'Rating': pd.Series([4.23, 3.24, 3.98, 2.56, 3.20, 4.6, 3.8])}
unsorted_df = pd.DataFrame(d)
print(unsorted_df)
sort_age = unsorted_df.sort_values(by="Age")
print("------排序后 按照[Age]排序\n", sort_age)
sort_age_rating = unsorted_df.sort_values(by=["Age", "Rating"],
ascending=[True, False])
print("------排序后 先[Age]后[Rating]排序\n", sort_age_rating)

    Name  Age  Rating
0    Tom   25    4.23
1  James   26    3.24
2  Ricky   25    3.98
3    Vin   23    2.56
4  Steve   30    3.20
5  Minsu   29    4.60
6   Jack   23    3.80
------排序后 按照[Age]排序
     Name  Age  Rating
3    Vin   23    2.56
6   Jack   23    3.80
0    Tom   25    4.23
2  Ricky   25    3.98
1  James   26    3.24
5  Minsu   29    4.60
4  Steve   30    3.20
------排序后 先[Age]后[Rating]排序
     Name  Age  Rating
6   Jack   23    3.80
3    Vin   23    2.56
0    Tom   25    4.23
2  Ricky   25    3.98
1  James   26    3.24
5  Minsu   29    4.60
4  Steve   30    3.20


## 代码3-19

In [36]:
import pandas as pd
import numpy as np
unsorted_df = pd.DataFrame (np.random. randn (8,2),
index=[1,4,6,2,3,5,0,7],columns = ['col2','col1'])
sorted_df = unsorted_df.sort_index(ascending=False)
print (unsorted_df)
print (sorted_df)

       col2      col1
1 -0.848795  2.063609
4  1.828442 -0.270021
6 -1.212310 -0.135058
2  0.253279  0.204364
3 -1.324224  1.174725
5 -0.334631 -2.396101
0  1.569236 -3.131366
7  0.151860 -1.041285
       col2      col1
7  0.151860 -1.041285
6 -1.212310 -0.135058
5 -0.334631 -2.396101
4  1.828442 -0.270021
3 -1.324224  1.174725
2  0.253279  0.204364
1 -0.848795  2.063609
0  1.569236 -3.131366


## 代码3-20

In [37]:
import pandas as pd
import numpy as np
unsorted_df = pd.DataFrame(np.random.randn(8,2),
index=[1,4,6,2,3,5,0,7], columns = ['col2','col1'])
sorted_df=unsorted_df.sort_index(axis=1)
print (sorted_df)

       col1      col2
1  0.045351 -1.220129
4 -0.659580 -1.296702
6  0.760674  1.162214
2  1.181489 -0.473988
3 -1.980036  0.745365
5  0.478243  0.150639
0  0.681424 -2.381049
7  0.444570 -1.056660


## 代码3-21

In [38]:
import pandas as pd
import numpy as np
unsorted_df = pd.DataFrame({'col1':[2,1,1,1],'col2':[1,3,2,4]})
sorted_df = unsorted_df.sort_values(by='col1')
print (sorted_df)

   col1  col2
1     1     3
2     1     2
3     1     4
0     2     1


## 代码3-22

In [4]:
import pandas as pd
import numpy as np
import pandas as pd
import numpy as np
unsorted_df = pd.DataFrame({'col1':[2,1,1,1],'col2':[1,3,2,4]})
sorted_df = unsorted_df.sort_values(by='col1',inplace=True)
print(unsorted_df)

   col1  col2
1     1     3
2     1     2
3     1     4
0     2     1


## 代码3-23

In [40]:
import pandas as pd
import numpy as np
unsorted_df = pd.DataFrame({'col1':[2,1,1,1],'col2':[1,3,2,4]})
sorted_df = unsorted_df.sort_values(by='col1' ,kind='mergesort')
print (sorted_df)

   col1  col2
1     1     3
2     1     2
3     1     4
0     2     1


## 代码3-24

In [25]:
import numpy as np
import pandas as pd
np.random.seed(1234)
df1 = pd.Series(2*np.random.normal(size = 100)+3)
df1

0     3.942870
1     0.618049
2     5.865414
3     2.374696
4     1.558823
        ...   
95    2.836106
96    2.310468
97    4.056576
98    0.862022
99    1.976237
Length: 100, dtype: float64

## 代码3-25

In [26]:
df1.count()

100

## 代码3-26

In [44]:
df1.sum()

307.0224566250873

## 代码3-27

In [45]:
df1.mean()

3.070224566250874

## 代码3-28

In [46]:
df1.median()

3.204555266776845

## 代码3-29

In [47]:
df1.std()

2.0014018533355777

## 代码3-30

In [48]:
df1.min()

-4.1270333212494705

## 代码3-31

In [50]:
df1.max()

7.781921030926066

## 代码3-32

In [51]:
df1.var()

4.005609378535085

## 代码3-33

In [52]:
df1.mad()

1.5112880411556109

## 代码3-34

In [53]:
df1.cumsum()

0       3.942870
1       4.560919
2      10.426333
3      12.801029
4      14.359852
         ...    
95    297.817153
96    300.127621
97    304.184197
98    305.046219
99    307.022457
Length: 100, dtype: float64

## 代码3-35

In [54]:
df1. mode()

0    -4.127033
1    -1.800907
2    -1.485370
3    -1.149955
4    -1.042510
        ...   
95    5.865414
96    6.091318
97    7.015686
98    7.061207
99    7.781921
Length: 100, dtype: float64

## 代码3-36

In [55]:
df1.abs()

0     3.942870
1     0.618049
2     5.865414
3     2.374696
4     1.558823
        ...   
95    2.836106
96    2.310468
97    4.056576
98    0.862022
99    1.976237
Length: 100, dtype: float64

## 代码3-37

In [56]:
df1.prod()

-6.968931241977193e+42

## 代码3-38

In [57]:
df1.cumprod()

0     3.942870e+00
1     2.436886e+00
2     1.429334e+01
3     3.394235e+01
4     5.291009e+01
          ...     
95   -4.364645e+41
96   -1.008437e+42
97   -4.090802e+42
98   -3.526363e+42
99   -6.968931e+42
Length: 100, dtype: float64

## 代码3-39

In [58]:
df1.describe()

count    100.000000
mean       3.070225
std        2.001402
min       -4.127033
25%        2.040101
50%        3.204555
75%        4.434788
max        7.781921
dtype: float64